from building import *

cwd     = GetCurrentDir()
src     = Glob('*.c') + Glob('*.cpp')
CPPPATH = [cwd + '/../inc']

group = DefineGroup('dlp_protocol', src, depend = [''], CPPPATH = CPPPATH)

Return('group')