################################################################################
# 自动生成的文件。不要编辑！
################################################################################

-include ../makefile.init

RM := rm -rf

# All of the sources participating in the build are defined here
-include sources.mk
-include rt-thread/src/subdir.mk
-include rt-thread/libcpu/arm/cortex-m4/subdir.mk
-include rt-thread/libcpu/arm/common/subdir.mk
-include rt-thread/components/utilities/ymodem/subdir.mk
-include rt-thread/components/utilities/utest/subdir.mk
-include rt-thread/components/utilities/ulog/backend/subdir.mk
-include rt-thread/components/utilities/ulog/subdir.mk
-include rt-thread/components/net/sal/src/subdir.mk
-include rt-thread/components/net/sal/socket/subdir.mk
-include rt-thread/components/net/sal/impl/subdir.mk
-include rt-thread/components/net/sal/dfs_net/subdir.mk
-include rt-thread/components/net/netdev/src/subdir.mk
-include rt-thread/components/net/at/src/subdir.mk
-include rt-thread/components/net/at/at_socket/subdir.mk
-include rt-thread/components/libc/posix/libdl/arch/subdir.mk
-include rt-thread/components/libc/posix/libdl/subdir.mk
-include rt-thread/components/libc/posix/io/stdio/subdir.mk
-include rt-thread/components/libc/posix/io/poll/subdir.mk
-include rt-thread/components/libc/compilers/newlib/subdir.mk
-include rt-thread/components/libc/compilers/common/subdir.mk
-include rt-thread/components/finsh/subdir.mk
-include rt-thread/components/fal/src/subdir.mk
-include rt-thread/components/fal/samples/porting/subdir.mk
-include rt-thread/components/drivers/watchdog/subdir.mk
-include rt-thread/components/drivers/spi/sfud/src/subdir.mk
-include rt-thread/components/drivers/spi/subdir.mk
-include rt-thread/components/drivers/serial/subdir.mk
-include rt-thread/components/drivers/rtc/subdir.mk
-include rt-thread/components/drivers/mtd/subdir.mk
-include rt-thread/components/drivers/misc/subdir.mk
-include rt-thread/components/drivers/ipc/subdir.mk
-include rt-thread/components/drivers/i2c/subdir.mk
-include rt-thread/components/dfs/src/subdir.mk
-include rt-thread/components/dfs/filesystems/devfs/subdir.mk
-include packages/vconsole-latest/subdir.mk
-include packages/minIni-v1.2.0/dev/subdir.mk
-include packages/littlefs-latest/subdir.mk
-include packages/at_device-latest/src/subdir.mk
-include packages/at_device-latest/samples/subdir.mk
-include packages/at_device-latest/class/n720/subdir.mk
-include packages/agile_led-v1.1.1/src/subdir.mk
-include packages/CmBacktrace-v1.4.1/subdir.mk
-include packages/CherryUSB-latest/port/dwc2/subdir.mk
-include packages/CherryUSB-latest/core/subdir.mk
-include packages/CherryUSB-latest/class/cdc/subdir.mk
-include libraries/hc32f460_ddl/drivers/hc32_ll_driver/src/subdir.mk
-include libraries/hc32f460_ddl/drivers/cmsis/Device/HDSC/hc32f4xx/Source/GCC/subdir.mk
-include libraries/hc32f460_ddl/drivers/cmsis/Device/HDSC/hc32f4xx/Source/subdir.mk
-include libraries/hc32_drivers/subdir.mk
-include build/packages/minIni-v1.2.0/dev/subdir.mk
-include build/packages/littlefs-latest/subdir.mk
-include build/packages/at_device-latest/src/subdir.mk
-include build/packages/at_device-latest/samples/subdir.mk
-include build/packages/at_device-latest/class/n720/subdir.mk
-include build/packages/agile_led-v1.1.1/src/subdir.mk
-include build/packages/CmBacktrace-v1.4.1/subdir.mk
-include build/packages/CherryUSB-latest/port/dwc2/subdir.mk
-include build/packages/CherryUSB-latest/core/subdir.mk
-include build/packages/CherryUSB-latest/class/cdc/subdir.mk
-include build/kernel/src/subdir.mk
-include build/kernel/libcpu/arm/cortex-m4/subdir.mk
-include build/kernel/libcpu/arm/common/subdir.mk
-include build/kernel/components/utilities/ymodem/subdir.mk
-include build/kernel/components/utilities/utest/subdir.mk
-include build/kernel/components/utilities/ulog/backend/subdir.mk
-include build/kernel/components/utilities/ulog/subdir.mk
-include build/kernel/components/net/sal/src/subdir.mk
-include build/kernel/components/net/sal/socket/subdir.mk
-include build/kernel/components/net/sal/impl/subdir.mk
-include build/kernel/components/net/sal/dfs_net/subdir.mk
-include build/kernel/components/net/netdev/src/subdir.mk
-include build/kernel/components/net/at/src/subdir.mk
-include build/kernel/components/net/at/at_socket/subdir.mk
-include build/kernel/components/libc/posix/pthreads/subdir.mk
-include build/kernel/components/libc/posix/libdl/arch/subdir.mk
-include build/kernel/components/libc/posix/libdl/subdir.mk
-include build/kernel/components/libc/posix/io/stdio/subdir.mk
-include build/kernel/components/libc/posix/io/poll/subdir.mk
-include build/kernel/components/libc/posix/delay/subdir.mk
-include build/kernel/components/libc/compilers/newlib/subdir.mk
-include build/kernel/components/libc/compilers/common/subdir.mk
-include build/kernel/components/finsh/subdir.mk
-include build/kernel/components/fal/src/subdir.mk
-include build/kernel/components/fal/samples/porting/subdir.mk
-include build/kernel/components/drivers/watchdog/subdir.mk
-include build/kernel/components/drivers/spi/sfud/src/subdir.mk
-include build/kernel/components/drivers/spi/subdir.mk
-include build/kernel/components/drivers/serial/subdir.mk
-include build/kernel/components/drivers/sensors/subdir.mk
-include build/kernel/components/drivers/rtc/subdir.mk
-include build/kernel/components/drivers/pm/subdir.mk
-include build/kernel/components/drivers/mtd/subdir.mk
-include build/kernel/components/drivers/misc/subdir.mk
-include build/kernel/components/drivers/ipc/subdir.mk
-include build/kernel/components/drivers/hwcrypto/subdir.mk
-include build/kernel/components/dfs/src/subdir.mk
-include build/kernel/components/dfs/filesystems/devfs/subdir.mk
-include build/board/subdir.mk
-include build/applications/upp_protocol/subdir.mk
-include build/applications/src/subdir.mk
-include build/applications/dlp_protocol/subdir.mk
-include build/applications/subdir.mk
-include board/subdir.mk
-include applications/upp_protocol/src/subdir.mk
-include applications/src/subdir.mk
-include applications/dlp_protocol/src/subdir.mk
-include subdir.mk
-include objects.mk

ifneq ($(MAKECMDGOALS),clean)
ifneq ($(strip $(ASM_DEPS)),)
-include $(ASM_DEPS)
endif
ifneq ($(strip $(S_DEPS)),)
-include $(S_DEPS)
endif
ifneq ($(strip $(S_UPPER_DEPS)),)
-include $(S_UPPER_DEPS)
endif
ifneq ($(strip $(C_DEPS)),)
-include $(C_DEPS)
endif
endif

-include ../makefile.defs

# Add inputs and outputs from these tool invocations to the build variables 
SECONDARY_FLASH += \
rtthread.bin \

SECONDARY_SIZE += \
rtthread.siz \


# 所有目标
all: rtthread.elf secondary-outputs

# 工具调用
rtthread.elf: $(OBJS) $(USER_OBJS)
	arm-none-eabi-gcc -T "D:\RT-ThreadStudio\workspace\Concentrator_v0_0_12\board\linker_scripts\link.ld" -Wl,-Map,"rtthread.map" --specs=nano.specs -mcpu=cortex-m4 -mthumb -mfpu=fpv4-sp-d16 -mfloat-abi=hard -ffunction-sections -fdata-sections -Wl,--gc-sections,-Map=rtthread.map,-cref,-u,Reset_Handler -o "rtthread.elf" $(OBJS) $(USER_OBJS) $(LIBS)

rtthread.bin: rtthread.elf
	arm-none-eabi-objcopy -O binary "rtthread.elf"  "rtthread.bin"

rtthread.siz: rtthread.elf
	arm-none-eabi-size --format=berkeley "rtthread.elf"

# 其他目标
clean:
	-$(RM) $(OBJS)$(SECONDARY_FLASH)$(SECONDARY_SIZE)$(ASM_DEPS)$(S_DEPS)$(S_UPPER_DEPS)$(C_DEPS) rtthread.elf
	-@echo ' '

secondary-outputs: $(SECONDARY_FLASH) $(SECONDARY_SIZE)

.PHONY: all clean dependents

-include ../makefile.targets
