################################################################################
# 自动生成的文件。不要编辑！
################################################################################

ELF_SRCS := 
OBJ_SRCS := 
S_SRCS := 
ASM_SRCS := 
C_SRCS := 
S_UPPER_SRCS := 
O_SRCS := 
OBJS := 
SECONDARY_FLASH := 
SECONDARY_SIZE := 
ASM_DEPS := 
S_DEPS := 
S_UPPER_DEPS := 
C_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
applications/dlp_protocol/src \
applications/src \
applications/upp_protocol/src \
applications/wch/src \
board \
build/applications \
build/applications/dlp_protocol \
build/applications/src \
build/applications/upp_protocol \
build/board \
build/kernel/components/dfs/filesystems/devfs \
build/kernel/components/dfs/src \
build/kernel/components/drivers/hwcrypto \
build/kernel/components/drivers/ipc \
build/kernel/components/drivers/misc \
build/kernel/components/drivers/mtd \
build/kernel/components/drivers/pm \
build/kernel/components/drivers/rtc \
build/kernel/components/drivers/sensors \
build/kernel/components/drivers/serial \
build/kernel/components/drivers/spi \
build/kernel/components/drivers/spi/sfud/src \
build/kernel/components/drivers/watchdog \
build/kernel/components/fal/samples/porting \
build/kernel/components/fal/src \
build/kernel/components/finsh \
build/kernel/components/libc/compilers/common \
build/kernel/components/libc/compilers/newlib \
build/kernel/components/libc/posix/delay \
build/kernel/components/libc/posix/io/poll \
build/kernel/components/libc/posix/io/stdio \
build/kernel/components/libc/posix/libdl/arch \
build/kernel/components/libc/posix/libdl \
build/kernel/components/libc/posix/pthreads \
build/kernel/components/net/at/at_socket \
build/kernel/components/net/at/src \
build/kernel/components/net/netdev/src \
build/kernel/components/net/sal/dfs_net \
build/kernel/components/net/sal/impl \
build/kernel/components/net/sal/socket \
build/kernel/components/net/sal/src \
build/kernel/components/utilities/ulog/backend \
build/kernel/components/utilities/ulog \
build/kernel/components/utilities/utest \
build/kernel/components/utilities/ymodem \
build/kernel/libcpu/arm/common \
build/kernel/libcpu/arm/cortex-m4 \
build/kernel/src \
build/packages/CherryUSB-latest/class/cdc \
build/packages/CherryUSB-latest/core \
build/packages/CherryUSB-latest/port/dwc2 \
build/packages/CmBacktrace-v1.4.1 \
build/packages/agile_led-v1.1.1/src \
build/packages/at_device-latest/class/n720 \
build/packages/at_device-latest/samples \
build/packages/at_device-latest/src \
build/packages/littlefs-latest \
build/packages/minIni-v1.2.0/dev \
libraries/hc32_drivers \
libraries/hc32f460_ddl/drivers/cmsis/Device/HDSC/hc32f4xx/Source/GCC \
libraries/hc32f460_ddl/drivers/cmsis/Device/HDSC/hc32f4xx/Source \
libraries/hc32f460_ddl/drivers/hc32_ll_driver/src \
packages/CherryUSB-latest/class/cdc \
packages/CherryUSB-latest/core \
packages/CherryUSB-latest/port/dwc2 \
packages/CmBacktrace-v1.4.1 \
packages/agile_led-v1.1.1/src \
packages/at_device-latest/class/n720 \
packages/at_device-latest/samples \
packages/at_device-latest/src \
packages/littlefs-latest \
packages/minIni-v1.2.0/dev \
packages/netutils-latest/iperf \
packages/netutils-latest/netio \
packages/netutils-latest/ntp \
packages/netutils-latest/ping \
packages/netutils-latest/tcpdump \
packages/netutils-latest/telnet \
packages/netutils-latest/tftp \
packages/syswatch-latest/src \
packages/vconsole-latest \
rt-thread/components/dfs/filesystems/devfs \
rt-thread/components/dfs/src \
rt-thread/components/drivers/hwcrypto \
rt-thread/components/drivers/i2c \
rt-thread/components/drivers/ipc \
rt-thread/components/drivers/misc \
rt-thread/components/drivers/mtd \
rt-thread/components/drivers/rtc \
rt-thread/components/drivers/serial \
rt-thread/components/drivers/spi/sfud/src \
rt-thread/components/drivers/spi \
rt-thread/components/drivers/watchdog \
rt-thread/components/fal/samples/porting \
rt-thread/components/fal/src \
rt-thread/components/finsh \
rt-thread/components/libc/compilers/common \
rt-thread/components/libc/compilers/newlib \
rt-thread/components/libc/posix/io/poll \
rt-thread/components/libc/posix/io/stdio \
rt-thread/components/libc/posix/libdl/arch \
rt-thread/components/libc/posix/libdl \
rt-thread/components/net/at/at_socket \
rt-thread/components/net/at/src \
rt-thread/components/net/netdev/src \
rt-thread/components/net/sal/dfs_net \
rt-thread/components/net/sal/impl \
rt-thread/components/net/sal/socket \
rt-thread/components/net/sal/src \
rt-thread/components/utilities/ulog/backend \
rt-thread/components/utilities/ulog \
rt-thread/components/utilities/utest \
rt-thread/components/utilities/ymodem \
rt-thread/libcpu/arm/common \
rt-thread/libcpu/arm/cortex-m4 \
rt-thread/src \
. \

